### ISSUE TITLE
Edit in runtime

### ISSUE THREAD

**Issue by pedromoto4** [slycrel/JSTileMap#18]
Hi all well, 
I have a doubt, it is possible to edit the maps at runtime? 
I'd like to see more documentation on the project, there is some place where I can find? 

very grateful

**Comment by slycrel** [comment]
@pedromoto4 do you mind sharing your code for your add method?  It sounds like a number of people would like to use such a method.

**Comment by slycrel** [comment]
Added with #43

**Comment by thenick775** [comment]
A quick question, this method only changes the texture of an already existing tile in the layer if I am correct. Is there a way to add an entirely "new" tile to the layer using an existing gID like this method does? For example, I have a walls layer the player is not allowed to pass through, this method doesn't do anything to the layer (doesn't add a new tile itself) if an existing clear tile is not there to change. I would like my player to be able to walk through the tile I want to change in my walls layer before I add a new tile, but not be able to after I add a new tile at that coordinate. Thank you for your time!
