### ISSUE TITLE
cave shows low fps rate (=20)

### ISSUE THREAD

**Issue by F99** [slycrel/JSTileMap#20]
at first, great work slycrel.

when i go/tap to the sampleCave sample, it shows around 20fps on my iphone4 (not simulator) while drawing 49 nodes, 2 draws. this disencourages me for using jstilemap for larger levels. is or will there be a way around this? also, initialization of the scene seems to take quite a while.

regards, F99

**Comment by slycrel** [comment]
F99,
I hope you got your issues worked out and found a solution.

**Comment by F99** [comment]
Nope, kicked it in the can. It continued to show additional spontaneous lags around 100-200ms every minute or so. Not sure, if it sources from jstilemap. But guess rather not.
