### ISSUE TITLE
JSTileMap in Sprite Kit @2x problem

### ISSUE THREAD

**Issue by TazmanNZL** [slycrel/JSTileMap#22]
Here is my method:
1. I use Texture Packer Pro to import a set of 128x128 sprites.
2. I create both a tileSet.png & tileSet@2x.png  sprite sheet (using built in scaler)  So the 2x version is 128x128 and the 1x version is 64x64
3. I open Tiled and create a 32x20 map with 64x64 tiles.
4. I Import the sprite sheet tileSet.png which is 64x64 tiles. with 1 margin and 2 spacing. I layout a few tiles
5. I then save the map: level1.tmx
6. I open up Xcode which already has the JSTileMap files and libz framework added
7. I add the files:  tileSet.png , tileSet@2x.png and level1.tmx
8. I build the app and the tiles appear all jumbled.
9. i remove tileSet@2x.png and clean/delete the app from simulator and re-run the app the tiles are no longer jumbled but are twice the size!

I followed Ray Wenderlich's tutorial for Super Koala as he uses both 1x and 2x png sprite sheets in his tutorial and they appear fine.  He however doesn't explain how he created the tmx map in Tiled. So I am not sure why mine is not loading correctly.

I need to be able to use the @2x sprite sheets without the sprites being jumbled up. Otherwise the sprites are scaled up and look low quality.

**Comment by Wh1rlw1nd** [comment]
@slycrel Could you post an example code to explain how to properly load @1x and @2x tilesets in this particular situation described above? I am having the same situation and can't make it work with ,,force identical layouts'' in Texturepacker. All I can do for now is to load high-res map, or low-res map. JSTileMap is really, really useful library,  but some documentation or basic tutorials and tips for common solutions  would be nice. This is my question on stackoverflow about same problem : http://stackoverflow.com/questions/27921999/spritekit-and-jstilemap

**Comment by wraithseeker** [comment]
Hello whirlwind, I tried to follow the solution posted by TazmanNFL using the iOS simulator of iPad, however it does not seem to be working.

My tiles are still 32x32 instead of changing to 64x64. Could you mind posting the code or project that you solved it on so  I can have a look?

**Comment by TazmanNZL** [comment]
You should have a @2x version (64x64) and a standard version (32x32) of your
tiles png.

Your files should be within the same folder:

level1.tmx
Tiles@2x.png  (64x64 tiles)
Tiles.png  (32x32 tiles)

Inside the level1.tmx  it should only refer to the 32x32 version png.  Which
is Tiles.png in example above.  When you created your tmx file in tiled you
should have only used the 32x32 tiles. (You don¹t use the @2x version
anywhere).

If the app runs on a Retina device it will automatically select the @2x png
instead of the standard one.  Also what makes you think it is showing only
the 32x32 ones?  Is it the size of the tiles on screen?  64x64 tiles do look
small on an iPad screen as opposed to an iPhone screen.  This is where you
aspect size comes in for sprite kit:


// Create and configure the scene.

    LevelScene *scene = [[LevelScene alloc]initWithSize:skView.bounds.size
level:self.currentLevel];

    scene.scaleMode = SKSceneScaleModeAspectFill;

Hope this helps :)

Taz  

From:  wraithseeker <notifications@github.com>
Reply-To:  slycrel/JSTileMap
<reply+0083589d161c88c08881d28233b754c4e5bb19c2f6650af292cf000000011132b70a9
2a169ce02e180a8@reply.github.com>
Date:  Wednesday, 1 April 2015 8:27 am
To:  slycrel/JSTileMap <JSTileMap@noreply.github.com>
Cc:  Corey Jull <cbjull@vodafone.co.nz>
Subject:  Re: [JSTileMap] JSTileMap in Sprite Kit @2x problem (#22)


Hello whirlwind, I tried to follow the solution posted by TazmanNFL using
the iOS simulator of iPad, however it does not seem to be working.

My tiles are still 32x32 instead of changing to 64x64. Could you mind
posting the code or project that you solved it on so  I can have a look?

‹
Reply to this email directly or view it on GitHub
<https://github.com/slycrel/JSTileMap/issues/22#issuecomment-88218315> .

**Comment by wraithseeker** [comment]
Hello, I tried it out again and it worked thanks! However, I have encountered a new problem.

Support for iphone 6 plus with Tiles@3x.png seem to be causing JSTileMap to either not display the image or display all the random textures in the textureatlas

Have you found a solution to support iphone 6 and iphone 6 plus?

**Comment by opletin** [comment]
Hello, wraithseeker. I have the same issues. Did you find the solution?
