### ISSUE TITLE
Using different sizes of tile causing problems?

### ISSUE THREAD

**Issue by iank-** [slycrel/JSTileMap#26]
Hi there!

I'm trying to use JSTileMap with a tmx file I made. When it runs in the simulator I don't see a map at all, or any graphics, and it says there's 0 nodes. I'm not using @2x anywhere, but I am using different tile sizes. Basically I'm using a tile size of 64px and using source images that are multiples of 64 so the graphics all line up nicely.

I downloaded your physics example, and tried having my code load that tmx file instead, and it worked.

Just wondering if you have any ideas what could be causing the problem? It doesn't say error loading images in the console, so I don't think it's having trouble finding them. (I've added those to the app bundle anyways.)

I attached a couple screenshots just so you can see everything..

Thank you very much for your time!
Ian

![screen shot 2014-12-14 at 8 00 50 pm](https://cloud.githubusercontent.com/assets/4088366/5430507/f98cfe7e-83ce-11e4-99e7-de6e51284d99.png)
![screen shot 2014-12-14 at 7 59 55 pm](https://cloud.githubusercontent.com/assets/4088366/5430508/f9a84b3e-83ce-11e4-8cd7-e99c8aa0d464.png)

**Comment by slycrel** [comment]
If you can get me a sample project of what you are seeing I'm happy to take a look.

**Comment by slycrel** [comment]
Hi iank,
I hope you have solved your problem.  I am closing this due to missing information.  If you would like to re-visit this please open a new issue.
