### ISSUE TITLE
Streaming large tilemaps?

### ISSUE THREAD

**Issue by Rhuantavan** [slycrel/JSTileMap#28]
I am wondering if you have plans to support streaming tilemaps? I am talking about only loading visible tiles, while unloading off-screen ones.

Fattjake did some work in that regard: https://github.com/fattjake/JSTileMap/commit/01b5bacc8c5ccc1099e020276d204ba439a6d06c?diff=unified

Thanks!

**Comment by slycrel** [comment]
I've done some testing and unless something has changed in this regard, SpriteKit does a bunch of this for you in it's renderer.  I've not been able to get performance better than what I've gotten without these optimizations.  In fact, I've found the opposite, that it generally makes things worse to try and end-run around SpriteKit's bufferer in this area.  So I have no immediate plans to pursue this, though I'm not going to reject any pull requests that improve performance.  =)

**Comment by Rhuantavan** [comment]
Alright, I guess I am set then. :)
