### ISSUE TITLE
Bug in coordForPoint and Improvement

### ISSUE THREAD

**Issue by muvimotv** [slycrel/JSTileMap#29]
Hi!

I found an issue in coordForPoint

you are using _mapTileSize.width for y and _mapTileSize.height for x. This should be the opposite...

Also, one improvement i would suggest is the code below. In my case i have to stretch the map and this result in incorrect coord detection. So adjusting by the xScale and yScale makes it possible to have a stretched JSTimeMap and get the proper coord for a specific point...

- (CGPoint) coordForPoint:(CGPoint) inPoint
{
	// invert y axis
	inPoint.y = [self layerHeight] * self.map.yScale - inPoint.y;
	
	int x = (int)inPoint.x / (_mapTileSize.width * self.map.xScale);
	int y = (int)inPoint.y / (_mapTileSize.height * self.map.yScale);
	
	return CGPointMake(x, y);
}

**Comment by muvimotv** [comment]
additionally, pointForCoord should be changed as well like this:

- (CGPoint)pointForCoord:(CGPoint)coord
{
  return
    CGPointMake(coord.x * _mapTileSize.width*self.map.xScale + _mapTileSize.width*self.map.xScale / 2,
                [self layerHeight]*self.map.yScale - (coord.y * _mapTileSize.height*self.map.yScale + _mapTileSize.height*self.map.yScale / 2));
}

**Comment by slycrel** [comment]
Hi muvimotov,

I have looked at this recently and came to the conclusion that this method works as intended -- but I can see why you might make this change.  It depends on which type of coordinates you pass to this method, view coordinates or node coordinates.  Generally for touch-based coordinates for example you would do something like this, which avoids having to worry about the scale:

```
- (IBAction)tapAction:(UITapGestureRecognizer *)sender
{
	// get the touch point and invert it
	CGPoint inPoint = [sender locationInView:self.view];
	inPoint.y = self.view.frame.size.height - inPoint.y;
	
	// translate the point from the view location to a spriteKit location within our map
	CGPoint translatedPoint = [[AppDelegate gameScene] convertPointFromView:inPoint];
	translatedPoint = [[AppDelegate gameScene].map convertPoint:translatedPoint fromNode:[AppDelegate gameScene]];

	// do stuff with the point
}
```

**Comment by muvimotv** [comment]
Hi slycrel,

Thanks a lot for your reply.

Could you then explain why in your logic you are using _mapTileSize.width for y and _mapTileSize.height for x? 
That quite doesn't make sense to me, especially that for a scale of 1 they way you originally coded it was returning wrong values.
As for you solution, i'm not using a tap action, SpriteKit is offering TouchesBegan for that and the point that i'm using is directly the point from the node. I don't really understand why you would want to make so many conversions, this is using too many calculations to do something simple imo.
Thanks

**Comment by slycrel** [comment]
You're right on the width/height mismatch.  Not sure how I missed that part, my apologies.

I've always worked with gesture recognizers for my basic touch needs, and you do indeed need to go through that translation -- converting the touch to the view, then to the node within the scene, which handles all of that extra stuff for you.  I think you could skip the convertPointFromView if you get the touch directly like you are talking about.  I think there is also a UITouch helper to convert the point to the specific node that may do the conversion for you as well.

I hesitate to add the scaling math in there as I think it works differently if your scale is > 0 or < 0.  I may be mis-remembering though, it's been a while.
