### ISSUE TITLE
Unable to render 64x64 tiles

### ISSUE THREAD

**Issue by wraithseeker** [slycrel/JSTileMap#31]
I am having issues making a new HD tmx file (64x64) from SD (32x32) tilesize. Basically the 32x32 SD works fine but the HD tmx file cannot render any tiles. (I have already made sure they are of the correct resolution for the tiles)

The problem right now is that the tiles are unable to be rendered by spritekit unless I edit the tmx file of the HD to the tilesize of the SD. I have been able to render the tile on the screen by placing it randomly with code.

http://forum.mapeditor.org/t/unable-to-render-64x64-tiles/426/1 code over here

**Comment by slycrel** [comment]
I don't have much time right now to look into this, but it may be your naming conventions.  Have a look at this stackoverflow question that may have your answer.

http://stackoverflow.com/questions/21001806/how-does-jstilemap-handle-retina-and-ipad-iphone-tile-maps

**Comment by wraithseeker** [comment]
I am not using the ipad, or iphone or @2x suffix at the moment, will try to debug again tommorow.
