### ISSUE TITLE
Updating tiles after generating map from JSTileMap.

### ISSUE THREAD

**Issue by wraithseeker** [slycrel/JSTileMap#32]
I am using a TMX file with tilesize of 32x32 but I want to be able to control the size and images of the sprites generated from JSTileMap after creation. How would I be able to do that?

For example I want to load images of those tiles at 64x64 and resize them back to 32x32 but in the TMX file it is using the image of 32x32

**Comment by slycrel** [comment]
hi wraithseeker,
The TMX format is in pixels, not points.  So you would need to adjust your map size appropriately.  There have been some people with mixed success using the @2x iOS conventions to get higher res textures to load properly, but it is not the default behavior.
