### ISSUE TITLE
gestures dont work on test example for iphone in simulator

### ISSUE THREAD

**Issue by tibnew** [slycrel/JSTileMap#36]
I checked out latest version of JSTileMap project and ran it on iphone simulator.
When i double tap nothing happends. Other gestures dont seem to work either.
I checked connections from gestures to view and to handlers and everything should work correctly.
Not sure what i am doing wrong. Could you check this?

**Comment by slycrel** [comment]
It's been a while, but I think that the current test code only works on the iPad simulator, not on the phone simulator.

**Comment by tibnew** [comment]
It seems that my iPhone simulator glitched.
Touch events started working after simulator reboot.
